### ISSUE TITLE
Couldn't Open workbook - Excel Error & Chrome-pdf error #459  & adding new excel is not working.

### ISSUE THREAD

**Issue by A-Pradeep** [jsreport/jsreport#461]
@pofider  Hi , after running the command `$ npm i jsreport-xlsx@2.0.3 --save --save-exact` also , the issue is not solved. I'm still facing the error .

Even not able to add new `Excel` i.e. The `+` is not working for the `xlsx` template

```
Skipping active sync with server
4client.js?feeb7eb1d54e81c8af5a:51 Uncaught TypeError: Cannot read property 'defaults' of undefined
    at ImageUploadButton.openFileDialog (1.client.js:15576)
    at Function.OpenUpload (1.client.js:15614)
    at Object.onNew (1.client.js:15240)
    at Object.onNewClick (client.js?feeb7eb1d54e81c8af5a:78)
    at onClick (client.js?feeb7eb1d54e81c8af5a:19)
    at Object.r (client.js?feeb7eb1d54e81c8af5a:51)
    at a (client.js?feeb7eb1d54e81c8af5a:74)
    at Object.s [as executeDispatchesInOrder] (client.js?feeb7eb1d54e81c8af5a:74)
    at d (client.js?feeb7eb1d54e81c8af5a:3)
    at f (client.js?feeb7eb1d54e81c8af5a:3)
    at Array.forEach (<anonymous>)
    at n (client.js?feeb7eb1d54e81c8af5a:52)
    at Object.processEventQueue (client.js?feeb7eb1d54e81c8af5a:3)
    at r (client.js?feeb7eb1d54e81c8af5a:75)
    at Object.handleTopLevel [as _handleTopLevel] (client.js?feeb7eb1d54e81c8af5a:75)
    at a (client.js?feeb7eb1d54e81c8af5a:75)
DevTools failed to parse SourceMap: http://demo.com:5488/studio/assets/Component.js.map
```

_Originally posted by @A-Pradeep in https://github.com/jsreport/jsreport/issues/459#issuecomment-435274980_

**Comment by pofider** [comment]
Can you try the same with the fresh new installation of the latest jsreport and updates jsreport-xlsx?

**Comment by A-Pradeep** [comment]
Okay i'll try and let you know.

**Comment by A-Pradeep** [comment]
@pofider Hi , i've installed fresh new installation and updated the `jsreport-xlsx`  but im not able to add the new Excel template since , the `+` is not working.

![image](https://user-images.githubusercontent.com/37439293/47905785-f0797400-dead-11e8-8392-f6092ed447fb.png)

**Comment by pofider** [comment]
Ups, I am very sorry. Somehow I missed this during testing.
Now it is fixed. Please use 
```
npm i jsreport-xlsx@2.0.4 --save --save-exact
```

**Comment by A-Pradeep** [comment]
Hi , sorry but i'm still facing this `Workbook ` error!
https://playground.jsreport.net/w/anon/1~Ip0Agj

**Comment by pofider** [comment]
Well but the "Gantt project planner1" template works. (in your local installation)
The other one is new and I can confirm it doesn't work. I will have to dig down the excel xml and find out what is wrong.

**Comment by pofider** [comment]
Now I fixed also the second excel. Please update using
```
npm i jsreport-xlsx@2.0.5 --save --save-exact
```

This time the problem was that excel requires specific ordering of xml nodes and your excel were using an unknown element for us - "legacyDrawing". I wish excel xml wouldn't be so extravagant. :)

**Comment by A-Pradeep** [comment]
@pofider Hi ! the excel template is working fine now , but the button `Upload (edit) xlsx template`  is not working . Apart from that everything's cool .

**Comment by pofider** [comment]
Thanks. The button is fixed in 2.0.6.
Closing this.
